import mongoose, { Schema, Types, model } from "mongoose";

const productSchema=new Schema(
    {
        title:{//can be unique or not 
            type:String,
            required:true,
            trim:true
        },
        description:String,
        slug:{
            type:String,
            required:true
        },
        folderId:{
            type:String,
            required:true,
            unique:true
        },
        basePrice:{
            type:Number,
            required:true
        },
        discount:{
            type:Number,
            default:0
        },
        appliedPrice:{
            type:Number,
            required:true
        },
        stock:{
            type:Number,
            min:0,
            default:0,
            required:true
        },
        rate:{
            type:Number,
            min:0,
            max:5,
            default:0
        },
        addedBy:{
            type:Types.ObjectId,
            ref:'User',
            required:true
        },
        updatedBy:{
            type:Types.ObjectId,
            ref:'User'
        },
        brandId:{
            type:Types.ObjectId,
            ref:'Brand',
            required:true
        },
        categoryId:{
            type:Types.ObjectId,
            ref:'Category',
            required:true
        },
        subCategoryId:{
            type:Types.ObjectId,
            ref:'SubCategory',
            required:true
        },
        Images:[
            {
            secure_url:{type:String,required:true}
            ,public_id:{type:String,required:true,unique:true}
            }
        ],
        specifications:{
            type:Map,
            of:[String|Number]
        }

    },{
        timestamps:true
    })

export default mongoose.models.Product || model('Product',productSchema)